Io bytes
krakacubra/Core_Test_Automation_Course pull request #9
Opened 2018-04-01 17:03 UTC by krakacubra

Задание 1. Работа с байтовыми потоками ввода-вывода

Прочитайте файл, содержащий код на языке Java. Определите, какие ключевые слова языка Java это код содержит. Выведите эти слова и их количество в другой файл. Используйте только байтовые потоки ввода-вывода.

2018-04-05 17:12 UTC, AnnaS91 requested changes

2018-04-05 17:12 UTC, AnnaS91 commented on 04_JavaFundamentals_practice/src/main/java/byteFiles/IOByte.java
> +        reader.close();
очень неприятная ошибка может произойти. Вы считаете, что закрываете поток, но если произойдет ошибка, он останется открытым. Обязательно использование try-with-resources или хотя бы finally, если Вы пишите на 6-й версии

2018-04-05 17:12 UTC, AnnaS91 commented on 04_JavaFundamentals_practice/src/main/java/byteFiles/IOByte.java
> +        writer.close();
аналогично

2018-04-05 17:12 UTC, AnnaS91 commented on 04_JavaFundamentals_practice/src/main/java/byteFiles/IOByte.java
> +            String line=KeyWords.KEYWORDS.get(i) + " - " + countKeyWord[i]+ "\r\n";
Слова, которые в файле не присутствуют, выводить не нужно

2018-04-05 17:12 UTC, AnnaS91 commented on 04_JavaFundamentals_practice/src/main/java/byteFiles/IOByte.java
> +        int i;
а зачем Вам инициализация i до цикла?

2018-04-05 17:12 UTC, AnnaS91 commented on 04_JavaFundamentals_practice/src/test/java/byteFiles/ByteReaderTest.java
> +    private final static List<String> keyWords = Arrays.asList("abstract", "assert", "boolean", "break",
а почему не используете уже объявленный в  KeyWords?

2018-04-06 17:06 UTC, krakacubra commented on 04_JavaFundamentals_practice/src/main/java/byteFiles/IOByte.java
> +        int i;
чтобы использовать эту переменную после цикла, я ее передаю как размер массива создаваемого

2018-04-07 14:25 UTC, AnnaS91 approved these changes

2018-04-07 14:25 UTC, AnnaS91 commented on 04_JavaFundamentals_practice/src/test/java/byteFiles/ByteReaderTest.java
> +        test = new IOByte("C:\\Users\\ADMIN\\EPAM\\Core_Test_Automation_Course\\04_JavaFundamentals_practice\\" +
лучше в тестах тоже использовать относительные пути

2018-04-07 20:27 UTC, merged